name: v3 buildx
on:
  workflow_call:
    inputs:
      services: { type: string, required: true }
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: ${{ fromJSON(inputs.services) }}
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v4
      - run: echo "${{ matrix.service }}"
